add restore script for seafile backups using restic onto rpi5

diff --git a/raspberry-pi-5/tasks/4-backup-seafile/template-backup-seafile.sh.j2 b/raspberry-pi-5/tasks/4-backup-seafile/template-backup-seafile.sh.j2
--- a/raspberry-pi-5/tasks/4-backup-seafile/template-backup-seafile.sh.j2
+++ b/raspberry-pi-5/tasks/4-backup-seafile/template-backup-seafile.sh.j2
@@ -55,7 +55,8 @@ restic backup \
     /opt/seafile-data/seafile/conf \
     /opt/seafile-data/seafile/seafile-data \
     /opt/seafile-data/seafile/seahub-data \
-    --verbose --no-scan
+    --verbose
+RESTIC_EXIT_CODE=$?
 
 # To check snapshots run:
 # $ sudo -E restic snapshots
@@ -71,7 +72,7 @@ restic backup \
 echo "Pushover.net sending notification"
 
 TIMESTAMP=$(date +%FT%T)
-if [ $? -eq 0 ]; then
+if [ $RESTIC_EXIT_CODE -eq 0 ]; then
     curl --form-string "token={{ backup_pushover_token }}" \
          --form-string "user={{ backup_pushover_user }}" \
          --form-string "priority=-1" \
@@ -84,11 +85,12 @@ else
     curl --form-string "token={{ backup_pushover_token }}" \
          --form-string "user={{ backup_pushover_user }}" \
          --form-string "priority=1" \
-         --form-string "message=$TIMESTAMP: Some errors occurred during backups" \
+         --form-string "message=$TIMESTAMP: Some errors occurred during backups - error code: $RESTIC_EXIT_CODE" \
          https://api.pushover.net/1/messages.json
 
     echo ""
-    echo "$TIMESTAMP: Some error occurred during backup - error code: $?"
+    echo "$TIMESTAMP: Some error occurred during backup - error code: $RESTIC_EXIT_CODE"
+    exit 1
 fi
 
 set +x
